# 함수 넣지마 큰 변수 데이터 로더같은거 넣지말기 클래스 자체를 

mode : train
dir_data : "/home/suhohan/seyeon/datasets/"
name_data : 'pascalVOC2012' #'preprocessed' #'isbi' #"isbi" #'cifar-10' 
model_name : 'UNet'

dataset:
  image_dim : 2
  mode : train
  dir_data : "/home/suhohan/seyeon/datasets"
  name_data : 'pascalVOC2012'
  model_name : 'UNet'
  
train:
  num_epoch : 140
  batch_size : 32
  
  dir_checkpoint : ./checkpoints
  dir_log : ./log
  dir_result: ./result
  scope : segmentation
  num_freq_save : 50

created_model:

  lr : 0.0001
  model_name : 'UNet'
  nch_in : 1
  nch_out : 10
  gpu_id : 2

  ## softmax -2class or bce or nllloss 
  # 


  
  


